### ISSUE TITLE
Is there any configurations needed?

### ISSUE THREAD

**Issue by zhant09** [atiselsts/arbitrum-token-uniswap-lp#1]
When I run the [analyze_pools.py](https://github.com/atiselsts/arbitrum-token-uniswap-lp/blob/main/analyze_pools.py) code, I got the following error:

`requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x132108df0>: Failed to establish a new connection: [Errno 61] Connection refused'))`

It seems that I need to start a service in localhost at port 8545? Or is there any configurations needed to run this code?

**Comment by atiselsts** [comment]
You need to set environmental variable `PROVIDER_URL_ARBITRUM`, it should point to the URL of the your node provider, for example:

   `export PROVIDER_URL_ARBITRUM=https://arbitrum-mainnet.infura.io/v3/...`

where the "..." parts should be your Infura API key.

If it's not set then the script will try to connect to localhost.

**Comment by zhant09** [comment]
Thank you, it works for me now.
